// Adoption Request Create Constants
export const ADOPTION_REQUEST_CREATE_REQUEST = 'ADOPTION_REQUEST_CREATE_REQUEST'
export const ADOPTION_REQUEST_CREATE_SUCCESS = 'ADOPTION_REQUEST_CREATE_SUCCESS'
export const ADOPTION_REQUEST_CREATE_FAIL = 'ADOPTION_REQUEST_CREATE_FAIL'
export const ADOPTION_REQUEST_CREATE_RESET = 'ADOPTION_REQUEST_CREATE_RESET'

// Adoption Request Update Constants
export const ADOPTION_REQUEST_UPDATE_REQUEST = 'ADOPTION_REQUEST_UPDATE_REQUEST'
export const ADOPTION_REQUEST_UPDATE_SUCCESS = 'ADOPTION_REQUEST_UPDATE_SUCCESS'
export const ADOPTION_REQUEST_UPDATE_FAIL = 'ADOPTION_REQUEST_UPDATE_FAIL'
export const ADOPTION_REQUEST_UPDATE_RESET = 'ADOPTION_REQUEST_UPDATE_RESET'

// Adoption Request List Constants
export const ADOPTION_REQUEST_LIST_REQUEST = 'ADOPTION_REQUEST_LIST_REQUEST'
export const ADOPTION_REQUEST_LIST_SUCCESS = 'ADOPTION_REQUEST_LIST_SUCCESS'
export const ADOPTION_REQUEST_LIST_FAIL = 'ADOPTION_REQUEST_LIST_FAIL'

// Adoption Request List Based On Provider Constants
export const PROVIDER_ADOPTION_REQUEST_LIST_REQUEST = 'PROVIDER_ADOPTION_REQUEST_LIST_REQUEST'
export const PROVIDER_ADOPTION_REQUEST_LIST_SUCCESS = 'PROVIDER_ADOPTION_REQUEST_LIST_SUCCESS'
export const PROVIDER_ADOPTION_REQUEST_LIST_FAIL = 'PROVIDER_ADOPTION_REQUEST_LIST_FAIL'

// Adoption Request Delete Constants
export const ADOPTION_REQUEST_DELETE_REQUEST = 'ADOPTION_REQUEST_DELETE_REQUEST'
export const ADOPTION_REQUEST_DELETE_SUCCESS = 'ADOPTION_REQUEST_DELETE_SUCCESS'
export const ADOPTION_REQUEST_DELETE_FAIL = 'ADOPTION_REQUEST_DELETE_FAIL'

// Adoption Request Detail Constants
export const ADOPTION_REQUEST_DETAIL_REQUEST = 'ADOPTION_REQUEST_DETAIL_REQUEST'
export const ADOPTION_REQUEST_DETAIL_SUCCESS = 'ADOPTION_REQUEST_DETAIL_SUCCESS'
export const ADOPTION_REQUEST_DETAIL_FAIL = 'ADOPTION_REQUEST_DETAIL_FAIL'

// Adoption Request Status Update Constants
export const ADOPTION_REQUEST_STATUS_REQUEST = 'ADOPTION_REQUEST_STATUS_REQUEST'
export const ADOPTION_REQUEST_STATUS_SUCCESS = 'ADOPTION_REQUEST_STATUS_SUCCESS'
export const ADOPTION_REQUEST_STATUS_FAIL = 'ADOPTION_REQUEST_STATUS_FAIL'