// Condition Report Create
export const CONDITION_REPORTS_CREATE_REQUESTS =
  "CONDITION_REPORTS_CREATE_REQUESTS";
export const CONDITION_REPORTS_CREATE_SUCCESS =
  "CONDITION_REPORTS_CREATE_SUCCESS";
export const CONDITION_REPORTS_CREATE_FAIL = "CONDITION_REPORTS_CREATE_FAIL";

// Condition Report Update
export const CONDITION_REPORTS_UPDATE_REQUESTS =
  "CONDITION_REPORTS_UPDATE_REQUESTS";
export const CONDITION_REPORTS_UPDATE_SUCCESS =
  "CONDITION_REPORTS_UPDATE_SUCCESS";
export const CONDITION_REPORTS_UPDATE_FAIL = "CONDITION_REPORTS_UPDATE_FAIL";

// Condition Report Delete
export const CONDITION_REPORTS_DELETE_REQUESTS =
  "CONDITION_REPORTS_DELETE_REQUESTS";
export const CONDITION_REPORTS_DELETE_SUCCESS =
  "CONDITION_REPORTS_DELETE_SUCCESS";
export const CONDITION_REPORTS_DELETE_FAIL = "CONDITION_REPORTS_DELETE_FAIL";

// Condition Report List Pet
export const CONDITION_REPORTS_LIST_REQUESTS =
  "CONDITION_REPORTS_LIST_REQUESTS";
export const CONDITION_REPORTS_LIST_SUCCESS = "CONDITION_REPORTS_LIST_SUCCESS";
export const CONDITION_REPORTS_LIST_FAIL = "CONDITION_REPORTS_LIST_FAIL";

// Condition Report List
export const CONDITION_REPORTS_LIST_PET_REQUESTS =
  "CONDITION_REPORTS_LIST_PET_REQUESTS";
export const CONDITION_REPORTS_LIST_PET_SUCCESS =
  "CONDITION_REPORTS_LIST_PET_SUCCESS";
export const CONDITION_REPORTS_LIST_PET_FAIL =
  "CONDITION_REPORTS_LIST_PET_FAIL";

// Condition Report Detail
export const CONDITION_REPORTS_DETAIL_REQUESTS =
  "CONDITION_REPORTS_DETAIL_REQUESTS";
export const CONDITION_REPORTS_DETAIL_SUCCESS =
  "CONDITION_REPORTS_DETAIL_SUCCESS";
export const CONDITION_REPORTS_DETAIL_FAIL = "CONDITION_REPORTS_DETAIL_FAIL";

// Condition Report Update Status
export const CONDITION_REPORTS_STATUS_REQUESTS =
  "CONDITION_REPORTS_STATUS_REQUESTS";
export const CONDITION_REPORTS_STATUS_SUCCESS =
  "CONDITION_REPORTS_STATUS_SUCCESS";
export const CONDITION_REPORTS_STATUS_FAIL = "CONDITION_REPORTS_STATUS_FAIL";
