// CONVERSATION LIST CONSTANTS
export const CONVERSATION_LIST_REQUEST = "CONVERSATION_LIST_REQUEST";
export const CONVERSATION_LIST_SUCCESS = "CONVERSATION_LIST_SUCCESS";
export const CONVERSATION_LIST_FAIL = "CONVERSATION_LIST_FAIL";

// CONVERSATION CREATE CONSTANTS
export const CONVERSATION_CREATE_REQUEST = "CONVERSATION_CREATE_REQUEST";
export const CONVERSATION_CREATE_SUCCESS = "CONVERSATION_CREATE_SUCCESS";
export const CONVERSATION_CREATE_FAIL = "CONVERSATION_CREATE_FAIL";

// MESSAGES LIST CONSTANTS
export const MESSAGE_LIST_REQUEST = "MESSAGE_LIST_REQUEST";
export const MESSAGE_LIST_SUCCESS = "MESSAGE_LIST_SUCCESS";
export const MESSAGE_LIST_FAIL = "MESSAGE_LIST_FAIL";

// MESSAGES CREATE CONSTANTS
export const MESSAGE_CREATE_REQUEST = "MESSAGE_CREATE_REQUEST";
export const MESSAGE_CREATE_SUCCESS = "MESSAGE_CREATE_SUCCESS";
export const MESSAGE_CREATE_FAIL = "MESSAGE_CREATE_FAIL";

// ARCHIVES LIST CONSTANTS
export const ARCHIVES_LIST_REQUEST = "ARCHIVES_LIST_REQUEST";
export const ARCHIVES_LIST_SUCCESS = "ARCHIVES_LIST_SUCCESS";
export const ARCHIVES_LIST_FAIL = "ARCHIVES_LIST_FAIL";
