// Pet Offer List Reducer
export const PET_OFFER_LIST_REQUEST = 'PET_OFFER_LIST_REQUEST'
export const PET_OFFER_LIST_SUCCESS = 'PET_OFFER_LIST_SUCCESS'
export const PET_OFFER_LIST_FAIL = 'PET_OFFER_LIST_FAIL'

// Pet Offer List for Specific User Reducer
export const SPECIFIC_USER_PET_OFFER_LIST_REQUEST = 'SPECIFIC_USER_PET_OFFER_LIST_REQUEST'
export const SPECIFIC_USER_PET_OFFER_LIST_SUCCESS = 'SPECIFIC_USER_PET_OFFER_LIST_SUCCESS'
export const SPECIFIC_USER_PET_OFFER_LIST_FAIL = 'SPECIFIC_USER_PET_OFFER_LIST_FAIL'

// Pet Offer List for Provider Reducer
export const PROVIDER_PET_LIST_REQUEST = 'PROVIDER_PET_LIST_REQUEST'
export const PROVIDER_PET_LIST_SUCCESS = 'PROVIDER_PET_LIST_SUCCESS'
export const PROVIDER_PET_LIST_FAIL = 'PROVIDER_PET_LIST_FAIL'

// Pet Offer Details Reducer
export const PET_OFFER_DETAILS_REQUEST = 'PET_OFFER_DETAILS_REQUEST'
export const PET_OFFER_DETAILS_SUCCESS = 'PET_OFFER_DETAILS_SUCCESS'
export const PET_OFFER_DETAILS_FAIL = 'PET_OFFER_DETAILS_FAIL'

// Pet Offer Create Reducer
export const PET_OFFER_CREATE_REQUEST = 'PET_OFFER_CREATE_REQUEST'
export const PET_OFFER_CREATE_SUCCESS = 'PET_OFFER_CREATE_SUCCESS'
export const PET_OFFER_CREATE_FAIL = 'PET_OFFER_CREATE_FAIL'
export const PET_OFFER_CREATE_RESET = 'PET_OFFER_CREATE_RESET'
export const CHOOSE_TYPE = 'CHOOSE_TYPE'
export const PRE_CREATE_PET_OFFER = 'PRE_CREATE_PET_OFFER'

// Pet Offer Delete Reducer
export const PET_OFFER_DELETE_REQUEST = 'PET_OFFER_DELETE_REQUEST'
export const PET_OFFER_DELETE_SUCCESS = 'PET_OFFER_DELETE_SUCCESS'
export const PET_OFFER_DELETE_FAIL = 'PET_OFFER_DELETE_FAIL'

// Pet Offer Update Reducer
export const PET_OFFER_UPDATE_REQUEST = 'PET_OFFER_UPDATE_REQUEST'
export const PET_OFFER_UPDATE_SUCCESS = 'PET_OFFER_UPDATE_SUCCESS'
export const PET_OFFER_UPDATE_FAIL = 'PET_OFFER_UPDATE_FAIL'
export const PET_OFFER_UPDATE_RESET = 'PET_OFFER_UPDATE_RESET'

// Pet Offer Update Status
export const PET_OFFER_STATUS_REQUEST = 'PET_OFFER_STATUS_REQUEST'
export const PET_OFFER_STATUS_SUCCESS = 'PET_OFFER_STATUS_SUCCESS'
export const PET_OFFER_STATUS_FAIL = 'PET_OFFER_STATUS_FAIL'

