//Login reducer
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

//Register reducer
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

//Verification reducer
export const USER_VERIFICATION_REQUEST = 'USER_VERIFICATION_REQUEST'
export const USER_VERIFICATION_SUCCESS = 'USER_VERIFICATION_SUCCESS'
export const USER_VERIFICATION_FAIL = 'USER_VERIFICATION_FAIL'

//View profile reducer
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

//Update profile reducer
export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL'

//Dertail profile reducer
export const PROVIDER_DETAIL_REQUEST = 'PROVIDER_DETAIL_REQUEST'
export const PROVIDER_DETAIL_SUCCESS = 'PROVIDER_DETAIL_SUCCESS'
export const PROVIDER_DETAIL_FAIL = 'PROVIDER_DETAIL_FAIL'

//Google register reducer
export const GOOGLE_REGISTER_REQUEST = 'GOOGLE_REGISTER_REQUEST'
export const GOOGLE_REGISTER_SUCCESS = 'GOOGLE_REGISTER_SUCCESS'
export const GOOGLE_REGISTER_FAIL = 'GOOGLE_REGISTER_FAIL'

